
###
GET http://localhost:4004/odata/v4/nautical/NAVOYGH
###
DELETE http://localhost:4004/odata/v4/nautical/NAVOYGH/1000000

###
POST  http://localhost:4004/odata/v4/nautical/NAVOYGH
Content-Type: application/json

 {
    "VOYNO":1,
    "VOYNM": "Mahadev",
    "VNOMTK": "",
    "REFDOC": "",
    "DOCIND": 1,
    "VESSN": "",
    "VIMO": "",
    "CHTYP": "47678",
    "CHPNO": "",
    "CURRKEYS": "USD",
    "FRTCO": 30.56,
    "VSTAT": "Created",
    "VOYTY": "1000",
    "CARTY": "1234",
    "CURR": "USD",
    "FREGHT": 0,
    "PARTY": "not yet",
    "BIDTYPE": "2",
    "FRCOST": 0,
    "FRTU": "",
    "FRCOST_ACT": 0,
    "ZDELETE": "0",
    "REF_VOYNO": "empty"
 }


###
GET http://localhost:4004/odata/v4/nautical/NAVOYGH

{
"VOYNO_VOYNO":1003,    
"VOYNO_VOYNM": "hh",
"VLEGN": "1234567890",
"PORTC":"89jh",
"PORTN": "Port City",
"LOCNAM": "OilRef1",
"PDIST": "1500.456",
"VSPEED": "12",
"PPDAYS": "3",
"VSDAYS": "5",
"VETAD": "2023-12-10",
"VETAT": null,
"VETDD": "2023-12-15",
"VETDT": null,
"VWEAD": "1",
"PSTAT": "Plan",
"MATNR": "M123456789",
"MAKTX": "Material Description",
"CARGS": "5678",
"CARGU": "Tonnes",
"OTHCO_code": null,
"FRCOST_code": null,
"TOTCO_code": null
}


###
POST  http://localhost:4004/odata/v4/nautical/ZBTP_NAUTICAL_MariDistance
Content-Type: application/json

{
"from_port": "test",
"to_port": "testing",
"distance": "261"
}

###
DELETE  http://localhost:4004/odata/v4/nautical/NAVOYGIP/

###
PATCH   http://localhost:4004/odata/v4/nautical/NAVOYGIP/VOY2
Content-Type: application/json

{

"PORTN": "PCity"

}