###
GET http://localhost:4004/odata/v4/nautical/VOYTYP




###
POST  http://localhost:4004/odata/v4/nautical/ZBTP_NAUTICAL_MariDistance
Content-Type: application/json

{
"from_port": "test",
"to_port": "testing",
"distance": "261"
}

###
DELETE  http://localhost:4004/odata/v4/nautical/NAVOYGIP/

###
PATCH   http://localhost:4004/odata/v4/nautical/NAVOYGIP/VOY2
Content-Type: application/json

{

"PORTN": "PCity"

}